language: ruby
rvm:
- 2.2.3
script: bundle exec rspec spec
addons:
  code_climate:
    repo_token:
      secure: ch4POH+GHn+wcMb3p78X0vaBiJzsHICq6zDVnnmS7FNSw6TQ4tCC+x1zr+PyNTinrj3yyP6v9tpfoWLpCkgCkV9hoKF+IwQVNmO1WLmH95msCGdZcQGqJdLYn725urQjpCinMW1UbrWNkijNLAZlu9cqGM6vUz6T+BJkwrOFAkn5Pzuo3weuNZupS9m86cAgQL1J6arsdP6TCRZJGyeb5wN2ZJ3XqMnRoL3dPeXFabILg82TaVOTOt5aC13tnmpcSJvompaxGsF3ywb0pK5X79hw4IidiQaXeRc7oSr9IE+IIBrknwawPsOWEKb/Ct78M8qpQIzRKL8AOOJB7wutTg7obRmpjKPvCSvNGPW2d+Y6UaiCWoY6MMYLHLqxQZLa1q8y3VykhDIXUJoeEI9wOaalmf2KVNKuL0Cn6b8V4j4z0ygm9b05dWEha19Nh1Xz+qrtH+9kNKYM7N3eSCdYEvNWMFfys9ce5rbEyv+QPS3+DYKb6Siwl/b6O7omQRoywTT0i1EbRl0xiZEk2RriZCkv6OM6J14rvTR7o8hqFpXvpU5w7ic+InOK94W2epwNTJZChqJRpmhIMDtlA7lGLV2w7T83NFgnru/jv3E+6GUPvRRwo87lf46Rt6xYqCUrkm/ThNUrsaafubXr/eoVFEPIlfSlXHAhM51zKtZJUUk=
